#
# Zero-downtime deployment.
#
# Feel free to stop/start individual appN instances,
# and see how HAProxy reacts.
#

haproxy:
  image: haproxy:1.5.12
  restart: always
  volumes:
    - ./haproxy-2.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    - ./certificate.pem:/usr/local/etc/haproxy/certificate.pem:ro
  net: "host"


app1:
  build: app
  ports:
    - "3001:3000"
  links:
    - redisserver
  environment:
    - REDIS_HOST=redisserver

app2:
  build: app
  ports:
    - "3002:3000"
  links:
    - redisserver
  environment:
    - REDIS_HOST=redisserver


redisserver:
  image: williamyeh/redis:2.8.19
  restart: always
  volumes:
    - .:/data
    - ./redis.conf:/etc/redis/redis.conf:ro
  command:
    - start
